# port
server:
  port: 9010

# logging
logging:
  level:
    me.hanwook: debug

# spring
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem::orders
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

# grpc
grpc:
  server:
    port: 9090