# port
server:
  port: 9011

# logging
logging:
  level:
    me.hanwook: debug

# spring
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem::members
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
grpc:
  server:
    port: 9091
  client:
    orderServiceClient:
      address: static://localhost:9090
      negotiation-type: PLAINTEXT
